---
title: 'Correlaciones por Pares'
subtitle: 'Todas las Variables'
author: 'Ma Fernanda Serrano'
date: 2022-09-06
tags: ['diagramde de columnas', 'corelaciones por pares', 'Fer Serrano', 'Torrance']
output: hugodown::md_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#source('https://github.com/umontano/CBQ_comandos_SPSS_lab_ChyC/raw/main/correlation_graphics.R')
#source('https://github.com/umontano/CBQ_comandos_SPSS_lab_ChyC/raw/main/CBQ_comandosSPSS_lab_CHyC.R')
```

```{r, include=FALSE, echo=FALSE}

library('tidytext')
library('widyr')
library('ggplot2')
library('dplyr')
library('tidyr')
library('tibble')
library('psych')

col_graphic_paired_significant_corrs <- function()
{

merged_dataset <- factors %>%
	add_id_column_numero %>%
	merge(add_id_column_numero(scales), by='numero') %>%
	merge(add_id_column_numero(raven), by='numero') %>%
	merge(torrance, by='numero') %>%
	mutate(numero=as.numeric(numero)) %>%
	select(!starts_with('X')) %>%
	select(where(is.numeric))

tor <- merged_dataset %>%
    select(c(names(torrance), -numero))
torrest <- merged_dataset %>%
    select(!names(torrance))

#call scaterplots
corr_graph_scatters_list <- scatterplot_significant_correlations(tor, torrest, sign=0.05)

	pmat <- corr.test(torrest, tor)$p
	rmat <- cor(torrest, tor)
	rmat[pmat > 0.05] <- NA
	rmat[abs(rmat) < 0.20] <- NA

    gpairs_by_nontor <- rmat %>%
		data.frame %>%
		mutate(item1=rownames(.)) %>%
		pivot_longer(!item1, names_to='item2', values_to='correlation') %>%
		filter(! is.na(correlation)) %>%
		mutate(item2=reorder_within(item2, correlation, item1)) %>%
		#mutate(item2=gsub('___.+', '', item2, perl=T)) %>%
		ggplot(aes(correlation, item2)) + 
		geom_col() +
		scale_y_reordered() +
		facet_wrap(~item1, scale='free_y')



    gpairs_by_torrance <- rmat %>%
		data.frame %>%
		mutate(item2=rownames(.)) %>%
		pivot_longer(!item2, names_to='item1', values_to='correlation') %>%
		filter(! is.na(correlation)) %>%
		mutate(item2=reorder_within(item2, correlation, item1)) %>%
		#mutate(item2=gsub('___.+', '', item2, perl=T)) %>%
		ggplot(aes(correlation, item2, fill=item1)) + 
		geom_col() +
		scale_y_reordered() +
		facet_wrap(~item1, scale='free_y')

        gglist <- list(gpairs_by_torrance, gpairs_by_nontor, rmat, pmat)

        
return(gglist)
}

```
# SCATTER PLOTS
# Correlation Matrix
#  P-values Matrix
```{r}
gglist <- col_graphic_paired_significant_corrs()
```


```{r, print_corr_matrix}
#print(gglist[[3]])
```
```{r, print_pvalues_matrix}
#print(gglist[[4]])
```

# GRAPHICS
# PAIRED CORRELATIONS
## Grouped by Torrance

```{r, torrance_paired_correlations_graph, echo=FALSE}
gglist[[1]]
```
## Grouped by Temperament, Raven and Other Variables

```{r, nontor_paired_correlations_graph, echo=FALSE}
gglist[[2]]
```
