---
title: 'Torrance Histogramas y Frecuencias'
author: 'Ma Fernanda Serrano'
date: 2022-09-06
tags: ['histograma', 'frecuencia', 'Fer Serrano', 'Torrance']
toc: TRUE
toc_depth: 3
output: hugodown::md_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#source('https://github.com/umontano/CBQ_comandos_SPSS_lab_ChyC/raw/main/correlation_graphics.R')
```


# TORRANCE Histogrames
Shows raw and oulaiers-cleaned datasets frequency distribution, for each variable

## Notas
* Cleaning changes the distribution



```{r, torrance_raw_vs_cleaned_histogram_freq, echo = FALSE, warning = FALSE, message = FALSE}

boxplots_raw_cleaned_outlaiers <- function(raw_dataset, cleaned_dataset)
{
raw_dataset <- data.frame(lapply(raw_dataset, as.numeric))
library('ggplot2')
library('dplyr')
library('tidyr')


#lambda definition pipeline
long <- . %>% select(-numero) %>%
	pivot_longer( cols=everything(),
		names_to='variable',
		values_to='value')

#Creates longtidy formats and assign outlaiers status in variable outlaier_status
#raw to long pipeline
raw_dataset     <- raw_dataset     %>% long %>% mutate(outlaier_status='raw')
#cleaned to long pipeline
cleaned_dataset <- cleaned_dataset %>% long %>% mutate(outlaier_status='cleaned')
#Merge into a single long df
merged_dataset <- rbind(raw_dataset, cleaned_dataset)

print(
ggplot(merged_dataset, aes(value, fill=outlaier_status, col=outlaier_status)) +
geom_bar(alpha=0.5, position='stack', width=0.99) +
#geom_histogram(alpha=0.5, position='stack', binwidth=1) +
facet_wrap(~ variable, scales='free')
)

print(
ggplot(merged_dataset, aes(value, fill=outlaier_status, col=outlaier_status)) +
geom_freqpoly(alpha=0.5, position='stack', binwidth=4) +
facet_wrap(~ variable, scales='free')
)
}

boxplots_raw_cleaned_outlaiers(torrance_raw, torrance)

```
