---
title: 'xTenacidad, xPerfeccionismo. xDescriptivos'
subtitle: 'Altas Capacidades'
author: 'Ma. Fernanda Serrano'
date: 2024-03-21
tags: ['descriptivo', 'altas capacidades', 'numeric variables', 'Fer Serrano', 'tenacidad', 'perfeccionismo']
output: hugodown::md_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#source('https://github.com/umontano/CBQ_comandos_SPSS_lab_ChyC/raw/main/correlation_graphics.R')
#https://github.com/Mafer-sg/Altas-Capacidades.git
source('~/p/tenacidad/tenacidad.R')
source('~/p/tenacidad/boxplots_numeric_multicategory.R')
```
## STACKED BARS FOR LEVELS OF EMPF AND GRIT
SE ANALIZARÁN ESTAS DOS PRUEBAS QUE YA ESTÁN VALIDADAS PARA LOS INFORMES: grit (va de grit1-grit8). 
RANGOS: BAJO (1 - 4.5), MEDIO (4.6 - 6.1) Y ALTO (6.2 – 8.0) 
EMPF (EMPF1-EMPF35). RANGOS: BAJO (5 – 17), MEDIO (18 – 20), ALTO (21 – 22) Y SUPERIOR (23 – 25). 

```{r, dodge, echo = FALSE, warning = FALSE, message = FALSE}
## VERSION DODGE
barplots_list <- bars_multicat_multicat_mapped(results_leveled, categorical_data, 'dodge')
# SHOW PLOTS
barplots_list[[1]]
barplots_list[[2]]
```

```{r, range_levels, echo = FALSE, warning = FALSE, message = FALSE}
barplots_list <- bars_multicat_multicat_mapped(results_leveled, categorical_data, 'stack')
# SHOW PLOTS
barplots_list[[1]]
barplots_list[[2]]
```

# EMPF DESCRIPTIVE STATISTICS
## Descriptivos empf.
# GRIT DESCRIPTIVE STATISTICS
## Descriptivos GRIT.

## BOXPLOTS GRIT
```{r,tenacidad_grit, echo = FALSE, warning = FALSE, message = FALSE}
#boxplots_takes_1numeric_many_categoricals(grit_means, categorical_data)

## COMPUTE USING LAPPLY WITH MULTINUM AND MULTICAT DATAFRAMES
plots_list <- boxplots_multinum_multicat_mapped(numeric_data, categorical_data)
## SHOW FIRT PLOT IN LIST
print(plots_list[[1]])
```

## BOXPLOTS EMPF
```{r, empf, echo = FALSE, warning = FALSE, message = FALSE}
## THE SINGLE NUMERICAL COLUM FUNCTION IS
#boxplots_takes_1numeric_many_categoricals(empf_means, categorical_data)

## SHOW SECOND PLOT IN LIST
print(plots_list[[2]])
```
