name: Workdir docker render
on:
  push:
    paths:
      - 'docs/content/post/*/*.Rmd' # trigger on post Rmd files
      - 'docs/content/*/*.Rmd' # trigger on dir Rmd files
      - '.github/workflows/*.yml' # trigger on workflows
    branches:
      - main

jobs:
  capture-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
