name: Workdir docker render
on:
  push:
    paths:
      - 'docs/content/post/*/*.Rmd' # trigger on post Rmd files
      - 'docs/content/*/*.Rmd' # trigger on dir Rmd files
      - '.github/workflows/*.yml' # trigger on workflows
    branches:
      - main

jobs:
  capture-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: render with docker on workdir
        run: |
          docker run -v $(pwd):/app umontano/rhugodown Rscript -e "rmarkdown::render('index.Rmd', output_format = 'pdf_document')"
          cat index.pdf
          ls
          pwd
        working-directory: docs/content/post/Altas-Capacidades
