name: Workdir docker render
on:
  push:
    paths:
      - 'docs/content/post/*/zzzz*.Rmd' # trigger on post Rmd files
      - 'docs/content/*/zzzz*.Rmd' # trigger on dir Rmd files
      - '.github/workflows/*.yml' # trigger on workflows
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: render with docker on workdir
        run: |
          docker run -v $(pwd):/app umontano/verseh Rscript -e "rmarkdown::render('lista_mediciones_primco.Rmd', output_format = 'hugodown::md_document')"
          docker run -v $(pwd):/app umontano/verseh Rscript -e "rmarkdown::render('lista_mediciones_primco.Rmd', output_format = 'html_document')"
          docker run -v $(pwd):/app umontano/verseh Rscript -e "rmarkdown::render('lista_mediciones_primco.Rmd', output_format = 'pdf_document')"
        working-directory: docs/content/post/Altas-Capacidades

      - name: Hugo 0.80.0
        run: |
          docker run -v $(pwd):/app umontano/verseh hugo
          echo doneeeee
        working-directory: docs

      - name: test append
        run: |
          echo zzzzzzzz >> zzzz.zzz
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Rendered and pushed Rmd file"
          git push

